apiVersion: v1
kind: Service
metadata:
  name: pirateapps
spec:
  selector:
    app: pirateapps
  ports:
    - name: pirateapps
      port: placehodlder-port
      protocol: TCP
      targetPort: placehodlder-port