metadata:
  name: lidarr
  labels:
    tailandtraillabs.com/app:lidarr
spec:
  replicas: 1
  selector:
    matchLabels:
      tailandtraillabs.com/app:lidarr
  template:
    metadata:
      labels:
        tailandtraillabs.com/app:lidarr
    spec:
      containers:
      - name:lidarr
        image: lscr.io/linuxserver/lidarr:latest
        ports:
        - containerPort: 8686
        livenessProbe:
          httpGet:
            port: 8686
        readinessProbe:
          httpGet:
            port: 8686
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: lidarr-config