apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: signoz
  namespace: signoz
  annotations:
    external-dns.alpha.kubernetes.io/hostname: signoz.lab.tailandtraillabs.com
    external-dns.alpha.kubernetes.io/target: intrepid.hangar.bpfx.org
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`signoz.lab.tailandtraillabs.com`)
      services:
        - name: signoz
          port: 8080
  tls:
    secretName: wildcard-tls-prod
